"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-19 14:43:37.707485

The eleven tables of spec §7, plus the three things autogeneration cannot express:

1. the **pgvector extension** — guarded, because CREATE EXTENSION needs superuser when
   the extension is absent, and this database may be a hosted free tier where it is not;
2. **append-only triggers** on ``scores``, ``briefs`` and ``quota_ledger`` — spec §5.3
   and §5.4 put history and side effects out of reach of application bugs, so the
   enforcement lives in the database, not in a convention;
3. the **daily quota spend view** the health CLI reads (spec §9).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Tables whose rows may never change once written (spec §5.3, §5.4).
APPEND_ONLY_TABLES: tuple[str, ...] = ("scores", "briefs", "quota_ledger")


def _create_append_only_trigger(table: str) -> None:
    """Reject UPDATE and DELETE outright, whatever the application believes."""
    op.execute(
        f"""
        CREATE OR REPLACE FUNCTION ta_{table}_append_only()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION
                'table {table} is append-only (spec 5.3/5.4): % is not permitted; '
                'append a correction row instead', TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        f"""
        CREATE TRIGGER trg_{table}_append_only
        BEFORE UPDATE OR DELETE ON {table}
        FOR EACH ROW EXECUTE FUNCTION ta_{table}_append_only();
        """
    )


def _drop_append_only_trigger(table: str) -> None:
    op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_append_only ON {table}")
    op.execute(f"DROP FUNCTION IF EXISTS ta_{table}_append_only()")


def upgrade() -> None:
    # pgvector is part of the pinned stack (spec §11). Guarded so this migration also
    # runs on a database where the extension is already installed by a privileged role.
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
                CREATE EXTENSION vector;
            END IF;
        END
        $$;
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidates",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("phrase", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("mentions", sa.Integer(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'pruned', 'kept', 'briefed', 'dropped')",
            name=op.f("ck_candidates_status_known"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidates")),
        sa.UniqueConstraint("phrase", "category", name="uq_candidates_phrase"),
    )
    op.create_index(
        "ix_candidates_category_status", "candidates", ["category", "status"], unique=False
    )
    op.create_table(
        "eval_cases",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("input_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_keep", sa.Boolean(), nullable=False),
        sa.Column("expected_fad_label", sa.String(length=16), nullable=False),
        sa.Column("score_min", sa.Float(), nullable=False),
        sa.Column("score_max", sa.Float(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("baseline_score", sa.Float(), nullable=True),
        sa.Column("last_score", sa.Float(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "expected_fad_label IN ('fad', 'trend', 'evergreen')",
            name=op.f("ck_eval_cases_fad_label_known"),
        ),
        sa.CheckConstraint("score_min <= score_max", name=op.f("ck_eval_cases_score_band_ordered")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_cases")),
    )
    op.create_table(
        "llm_cache",
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("gate", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "gate IN ('planner', 'judge', 'writer')", name=op.f("ck_llm_cache_gate_known")
        ),
        sa.PrimaryKeyConstraint("cache_key", name=op.f("pk_llm_cache")),
    )
    op.create_index("ix_llm_cache_expires_at", "llm_cache", ["expires_at"], unique=False)
    op.create_table(
        "quota_ledger",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("operation", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "spend_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.CheckConstraint("amount > 0", name=op.f("ck_quota_ledger_amount_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quota_ledger")),
        sa.UniqueConstraint("run_id", "source_id", "operation", name="uq_quota_ledger_run_id"),
    )
    op.create_index(
        "ix_quota_ledger_source_id_spend_date",
        "quota_ledger",
        ["source_id", "spend_date"],
        unique=False,
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("layer_status", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'ok', 'degraded', 'failed', 'aborted')",
            name=op.f("ck_runs_status_known"),
        ),
        sa.CheckConstraint(
            "trigger IN ('nightly', 'hourly', 'manual', 'resume')",
            name=op.f("ck_runs_trigger_known"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index("ix_runs_started_at", "runs", ["started_at"], unique=False)
    op.create_table(
        "signals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("entity", sa.Text(), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("quote", sa.Text(), nullable=True),
        sa.Column("raw_hash", sa.String(length=64), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
        sa.UniqueConstraint("source_id", "entity", "metric", "ts", name="uq_signals_source_id"),
    )
    op.create_index("ix_signals_category_ts", "signals", ["category", "ts"], unique=False)
    op.create_index(
        "ix_signals_entity_metric_ts", "signals", ["entity", "metric", "ts"], unique=False
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("tier", sa.String(length=1), nullable=False),
        sa.Column("layers", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("schedule", sa.String(length=16), nullable=False),
        sa.Column("budget_per_day", sa.Integer(), nullable=False),
        sa.Column("rps", sa.Float(), nullable=False),
        sa.Column("cache_ttl_h", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("domains", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("watermark", sa.Text(), nullable=True),
        sa.Column("watermark_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (tier = 'A' AND 'L0' = ANY(layers))", name=op.f("ck_sources_tier_a_never_in_l0")
        ),
        sa.CheckConstraint("tier IN ('S', 'A')", name=op.f("ck_sources_tier_known")),
        sa.CheckConstraint("budget_per_day > 0", name=op.f("ck_sources_budget_positive")),
        sa.CheckConstraint("rps > 0", name=op.f("ck_sources_rps_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_table(
        "raw_items",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_raw_items_run_id_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_items")),
        sa.UniqueConstraint("source_id", "content_hash", name="uq_raw_items_source_id"),
    )
    op.create_index("ix_raw_items_fetched_at", "raw_items", ["fetched_at"], unique=False)
    op.create_table(
        "run_source_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("items_fetched", sa.Integer(), nullable=False),
        sa.Column("items_new", sa.Integer(), nullable=False),
        sa.Column("quota_spent", sa.Integer(), nullable=False),
        sa.Column("rate_limit_hits", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ok', 'degraded', 'failed', 'skipped')",
            name=op.f("ck_run_source_log_status_known"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_source_log_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_source_log")),
        sa.UniqueConstraint("run_id", "source_id", name="uq_run_source_log_run_id"),
    )
    op.create_index(
        "ix_run_source_log_source_id_started_at",
        "run_source_log",
        ["source_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "scores",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("candidate_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "scored_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("weights_version", sa.String(length=32), nullable=False),
        sa.Column("demand_velocity", sa.Float(), nullable=False),
        sa.Column("saturation", sa.Float(), nullable=False),
        sa.Column("buyer_pain", sa.Float(), nullable=False),
        sa.Column("money", sa.Float(), nullable=False),
        sa.Column("feasibility", sa.Float(), nullable=False),
        sa.Column("mgs", sa.Float(), nullable=False),
        sa.Column("fad_probability", sa.Float(), nullable=False),
        sa.Column("fad_label", sa.String(length=16), nullable=False),
        sa.Column("revenue_p10", sa.Float(), nullable=False),
        sa.Column("revenue_p50", sa.Float(), nullable=False),
        sa.Column("revenue_p90", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "fad_label IN ('fad', 'trend', 'evergreen')", name=op.f("ck_scores_fad_label_known")
        ),
        sa.CheckConstraint(
            "fad_probability >= 0 AND fad_probability <= 1",
            name=op.f("ck_scores_fad_probability_in_range"),
        ),
        sa.CheckConstraint("mgs >= 0 AND mgs <= 100", name=op.f("ck_scores_mgs_in_range")),
        sa.CheckConstraint(
            "revenue_p10 <= revenue_p50 AND revenue_p50 <= revenue_p90",
            name=op.f("ck_scores_revenue_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_scores_candidate_id_candidates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_scores_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scores")),
        sa.UniqueConstraint(
            "candidate_id", "run_id", "weights_version", name="uq_scores_candidate_id"
        ),
    )
    op.create_index("ix_scores_run_id_mgs", "scores", ["run_id", "mgs"], unique=False)
    op.create_table(
        "briefs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("score_id", sa.BigInteger(), nullable=False),
        sa.Column("candidate_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("verdict", sa.Text(), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_briefs_candidate_id_candidates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_briefs_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["score_id"], ["scores.id"], name=op.f("fk_briefs_score_id_scores"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_briefs")),
        sa.UniqueConstraint("run_id", "candidate_id", name="uq_briefs_run_id"),
    )
    # ### end Alembic commands ###

    # --- hand-written: the guarantees autogeneration cannot express ---------------
    for table in APPEND_ONLY_TABLES:
        _create_append_only_trigger(table)

    # Daily spend per source. Health reports burn against the registry budget; the
    # ledger stays the source of truth, so the view is derived and never authoritative.
    op.execute(
        """
        CREATE VIEW quota_spend_daily AS
        SELECT source_id,
               date_trunc('day', spend_date AT TIME ZONE 'UTC')::date AS spend_day,
               sum(amount)::bigint AS requests,
               count(*)::bigint AS ledger_rows
        FROM quota_ledger
        GROUP BY 1, 2;
        """
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS quota_spend_daily")
    for table in APPEND_ONLY_TABLES:
        _drop_append_only_trigger(table)

    # The pgvector extension is intentionally NOT dropped: other schemas in the same
    # database may depend on it, and re-creating it needs superuser.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("briefs")
    op.drop_index("ix_scores_run_id_mgs", table_name="scores")
    op.drop_table("scores")
    op.drop_index("ix_run_source_log_source_id_started_at", table_name="run_source_log")
    op.drop_table("run_source_log")
    op.drop_index("ix_raw_items_fetched_at", table_name="raw_items")
    op.drop_table("raw_items")
    op.drop_table("sources")
    op.drop_index("ix_signals_entity_metric_ts", table_name="signals")
    op.drop_index("ix_signals_category_ts", table_name="signals")
    op.drop_table("signals")
    op.drop_index("ix_runs_started_at", table_name="runs")
    op.drop_table("runs")
    op.drop_index("ix_quota_ledger_source_id_spend_date", table_name="quota_ledger")
    op.drop_table("quota_ledger")
    op.drop_index("ix_llm_cache_expires_at", table_name="llm_cache")
    op.drop_table("llm_cache")
    op.drop_table("eval_cases")
    op.drop_index("ix_candidates_category_status", table_name="candidates")
    op.drop_table("candidates")
    # ### end Alembic commands ###
