#!/usr/bin/env bash
# Trend Analyst — the gate.
#
# Runs every check the build brief requires and prints markdown with RAW output, so
# evidence is generated rather than remembered:
#
#     bash scripts/gate.sh > docs/evidence/P0.md
#
# Checks that cannot pass yet because their phase has not landed are reported as
# PENDING with the reason, and do not fail the gate. That is deliberate: a gate that
# has to be edited to stay honest stops being evidence.
#
# Exit code: 0 when every runnable check passes, 1 otherwise.
set -uo pipefail

cd "$(dirname "$0")/.." || exit 2
export UV_PYTHON_DOWNLOADS=never UV_NO_MANAGED_PYTHON=1

failures=0
pendings=0

header() {
  printf '\n### %s\n\n' "$1"
}

check() { # check <title> <command...>
  local title="$1"
  shift
  header "$title"
  printf '```console\n$ %s\n' "$*"
  local out
  if out="$("$@" 2>&1)"; then
    printf '%s\n```\n\n**RESULT: PASS**\n' "$out"
  else
    printf '%s\n```\n\n**RESULT: FAIL (exit %s)**\n' "$out" "$?"
    failures=$((failures + 1))
  fi
}

pending() { # pending <title> <reason> <command...>
  local title="$1" reason="$2"
  shift 2
  pendings=$((pendings + 1))
  header "$title"
  printf '```console\n$ %s\n' "$*"
  printf '%s\n```\n\n**RESULT: PENDING — %s**\n' "$("$@" 2>&1)" "$reason"
}

# --- environment -------------------------------------------------------------
printf '# Trend Analyst — evidence log\n\n'
printf 'Generated by `scripts/gate.sh` on %s.\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
printf '\nInterpreter: `%s`\n' "$(uv run python -c 'import sys; print(sys.version.split()[0] + " (" + sys.executable + ")")' 2>/dev/null)"

# --- always runnable ---------------------------------------------------------
check "pytest — no database, no network" uv run pytest -q -m "not db"
check "ruff — lint clean" uv run ruff check .
check "mypy — strict, python_version=3.12" uv run mypy src config

# --- needs Postgres ----------------------------------------------------------
if uv run python -c "
import socket, sys
s = socket.socket(); s.settimeout(2)
sys.exit(0 if s.connect_ex(('127.0.0.1', 5432)) == 0 else 1)
" 2>/dev/null; then
  check "pytest — full suite against local Postgres + pgvector" uv run pytest -q
  if [ -f alembic.ini ] && compgen -G "migrations/versions/*.py" >/dev/null; then
    check "alembic — upgrade head" uv run alembic upgrade head
    check "alembic — zero drift between models and migrations" uv run alembic check
  else
    pending "alembic — upgrade head" "migrations land in bean P0-T5" uv run alembic upgrade head
  fi
else
  pending "pytest — full suite" "no Postgres reachable on 127.0.0.1:5432 (run: wsl -d Ubuntu -u root -- bash scripts/provision_pg.sh)" uv run pytest -q
fi

# --- needs the health CLI (P0-T7) -------------------------------------------
if grep -q 'STUB_PHASE = "P0-T7"' src/trend_analyst/monitor/health.py 2>/dev/null; then
  pending "health CLI — empty-but-healthy" "the health CLI is implemented in bean P0-T7" \
    uv run python -m trend_analyst.health
else
  check "health CLI — empty-but-healthy (exit 0)" uv run python -m trend_analyst.health --json
fi

# --- summary -----------------------------------------------------------------
header "Summary"
if [ "$failures" -eq 0 ]; then
  printf 'GATE: PASS (%s pending)\n' "$pendings"
  exit 0
fi
printf 'GATE: FAIL — %s check(s) failed\n' "$failures"
exit 1
