#!/usr/bin/env bash
# Trend Analyst — the gate.
#
# Runs every check the build brief requires and prints markdown with RAW output, so
# evidence is generated rather than remembered:
#
#     bash scripts/gate.sh > docs/evidence/P0-gate.md
#
# Checks that cannot pass yet because their phase has not landed are reported as
# PENDING with the reason, and do not fail the gate. That is deliberate: a gate that
# has to be edited to stay honest stops being evidence.
#
# Exit code: 0 when every runnable check passes, 1 otherwise.
set -uo pipefail

cd "$(dirname "$0")/.." || exit 2
export UV_PYTHON_DOWNLOADS=never UV_NO_MANAGED_PYTHON=1

failures=0
pendings=0

header() {
  printf '\n### %s\n\n' "$1"
}

check() { # check <title> <command...>
  local title="$1"
  shift
  header "$title"
  printf '```console\n$ %s\n' "$*"
  local out
  if out="$("$@" 2>&1)"; then
    printf '%s\n```\n\n**RESULT: PASS**\n' "$out"
  else
    printf '%s\n```\n\n**RESULT: FAIL (exit %s)**\n' "$out" "$?"
    failures=$((failures + 1))
  fi
}

pending() { # pending <title> <reason> <command...>
  local title="$1" reason="$2"
  shift 2
  pendings=$((pendings + 1))
  header "$title"
  printf '```console\n$ %s\n' "$*"
  printf '%s\n```\n\n**RESULT: PENDING — %s**\n' "$("$@" 2>&1)" "$reason"
}

# --- environment -------------------------------------------------------------
printf '# Trend Analyst — evidence log\n\n'
printf 'Generated by `scripts/gate.sh` on %s.\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
printf '\nInterpreter: `%s`\n' "$(uv run python -c 'import sys; print(sys.version.split()[0] + " (" + sys.executable + ")")' 2>/dev/null)"

# --- always runnable ---------------------------------------------------------
check "pytest — no database, no network" uv run pytest -q -m "not db"
check "ruff — lint clean" uv run ruff check .
check "mypy — strict, python_version=3.12" uv run mypy src config

# --- configuration ------------------------------------------------------------
config_cli_probe() {
  uv run python - <<'PY'
import json
import subprocess
import sys

out = subprocess.run(
    [sys.executable, "-m", "config.cli", "show", "--json"],
    capture_output=True,
    text=True,
    check=True,
)
data = json.loads(out.stdout)
layers = ", ".join(
    f"{layer['label']}={'loaded' if layer['exists'] else 'absent'}" for layer in data["layers"]
)
redacted = data["settings"]["db"]["url"] in ("", "***")
print(f"layers (high->low): {layers}")
print(f"credentials configured: {sum(1 for ok in data['credentials_configured'].values() if ok)}")
print(f"db.url redacted: {redacted}")
assert redacted, "the config CLI leaked a secret"
PY
}
check "config CLI — every layer resolved, secrets redacted" config_cli_probe

# --- registry ------------------------------------------------------------------
registry_probe() {
  uv run python - <<'PY'
import subprocess
import sys

out = subprocess.run(
    [sys.executable, "-m", "config.cli", "registry", "--json"],
    capture_output=True,
    text=True,
    check=True,
)
import json

data = json.loads(out.stdout)
summary = data["summary"]
print(
    f"{summary['total']} sources ({summary['tier_s']} Tier S, {summary['tier_a']} Tier A) · "
    f"{summary['enabled']} enabled, {summary['disabled']} disabled"
)
print(f"L0 collect: {summary['l0']} · L2 enrich: {summary['l2']}")
print(f"execution order starts: {', '.join(s['id'] for s in data['sources'][:3])} ...")
print(f"egress allowlist entries: {sum(len(v) for v in data['allowed_domains'].values())}")

l0 = [s for s in data["sources"] if "L0" in s["layers"]]
assert all(s["tier"] == "S" for s in l0), "Tier A slipped into L0"
assert all(s["enabled"] for s in l0), "an L0 source is disabled"
# An enabled Tier-A source must actually run: resolve its module and demand the plugin
# class with the matching id (the same rule `load_plugin` enforces, minus the registry
# budgets it already validated at load). SearchAPI is enabled with a live-verified
# plugin; the rest ship disabled.
import importlib

from trend_analyst.sources.base import SourcePlugin

for source in data["sources"]:
    if source["tier"] != "A" or not source["enabled"]:
        continue
    module = importlib.import_module(source["module"])
    found = [
        member for _, member in vars(module).items()
        if isinstance(member, type) and issubclass(member, SourcePlugin)
        and member is not SourcePlugin and member.id == source["id"]
    ]
    assert found, f"enabled Tier-A source {source['id']} defines no plugin for its id"
    print(f"Tier-A enabled and loadable: {source['id']}")
enabled_a = sorted(s["id"] for s in data["sources"] if s["tier"] == "A" and s["enabled"])
assert enabled_a == ["searchapi"], f"unexpected enabled Tier-A set: {enabled_a}"
PY
}
check "source registry — catalog, execution order, Tier-A never in L0" registry_probe

# --- L0 collection, replayed from the recorded fixtures (P1) ------------------
l0_replay_probe() {
  uv run python - <<'PY'
import json
import subprocess
import sys

SOURCES = ["--source", "hn_firebase", "--source", "wiki_pageviews", "--source", "arctic_shift"]

def run() -> dict:
    out = subprocess.run(
        [sys.executable, "-m", "trend_analyst.pipeline.orchestrator",
         "--fixtures", "tests/data", "--json", *SOURCES],
        capture_output=True, text=True, check=True,
    )
    # The CLI emits ONE document per invocation; a plain L0 run nests it under "l0".
    return json.loads(out.stdout)["l0"]

first = run()
second = run()
print(f"run 1: status={first['status']} signals={first['items_new']} "
      f"requests={first['quota_spent']}")
print(f"run 2: status={second['status']} signals={second['items_new']} "
      f"requests={second['quota_spent']}")
for outcome in second["outcomes"]:
    print(f"  {outcome['source_id']:<20} {outcome['status']:<8} "
          f"new={outcome['items_new']:<4} parsed={outcome['signals_parsed']:<4} "
          f"requests={outcome['quota_spent']}")
assert second["items_new"] == 0, "a repeated L0 run must store no new signals"
assert all(o["signals_parsed"] == 0 for o in second["outcomes"]), (
    "a repeated L0 run must not re-parse identical payloads"
)
PY
}
check "L0 replay — repeated run stores and parses nothing new" l0_replay_probe

# --- database reachability (Neon, per the configured DSN — never localhost) ----
db_reachable() {
  # One query against the real DSN: a socket probe cannot know which host the
  # settings point at, and the old 127.0.0.1 probe lied after the move to Neon.
  uv run python -c "
from sqlalchemy import create_engine, text
from config.settings import load_settings
from pathlib import Path
try:
    dsn = load_settings(Path('config')).db.dsn
    with create_engine(dsn, connect_args={'connect_timeout': 8}).connect() as c:
        c.execute(text('select 1'))
except Exception:
    raise SystemExit(1)
" 2>/dev/null
}

# --- registry → database sync (P0-T6) -----------------------------------------
if db_reachable; then
  check "registry sync — second run is a no-op" uv run python -m scripts.sync_sources
  check "registry sync — idempotent (dry run reports zero changes)" \
    uv run python -m scripts.sync_sources --dry-run
else
  pending "registry sync" "database unreachable (check the Neon DSN, USER_SETUP.md §1)" \
    uv run python -m scripts.sync_sources
fi

# --- needs Postgres ----------------------------------------------------------
if db_reachable; then
  check "pytest — full suite against Postgres + pgvector" uv run pytest -q
  if [ -f alembic.ini ] && compgen -G "migrations/versions/*.py" >/dev/null; then
    check "alembic — upgrade head" uv run alembic upgrade head
    check "alembic — zero drift between models and migrations" uv run alembic check
  else
    pending "alembic — upgrade head" "migrations land in bean P0-T5" uv run alembic upgrade head
  fi
else
  pending "pytest — full suite" "no Postgres reachable (check the Neon DSN, USER_SETUP.md §1)" uv run pytest -q
fi

p2_probe() {
# P2 acceptance: the ranked table renders end-to-end from L0 data, snapshots are versioned,
# and replaying the same lake reproduces the same scores (spec 5.4, hash-asserted in CI).
# --fixtures means the Extractor runs on the deterministic heuristic stand-in: no network,
# no spend, and the determinism assertion is meaningful rather than a measure of model luck.
local first second hash1 hash2
first=$(uv run python -m trend_analyst.pipeline.orchestrator --layers L1,L3 --top 3 --fixtures tests/data --json 2>/dev/null)
second=$(uv run python -m trend_analyst.pipeline.orchestrator --layers L1,L3 --top 3 --fixtures tests/data --json 2>/dev/null)
hash1=$(printf '%s' "$first" | uv run python -c 'import json,sys; print(json.load(sys.stdin)["decide"]["snapshot_hash"])')
hash2=$(printf '%s' "$second" | uv run python -c 'import json,sys; print(json.load(sys.stdin)["decide"]["snapshot_hash"])')
json_out=$(mktemp)
printf '%s' "$first" > "$json_out"
# NB: the payload goes through a file, not a pipe: with `python - <<HEREDOC` the heredoc IS
# stdin, so a piped payload is never read (the first draft of this check did exactly that and
# failed silently while still reporting PASS).
uv run python - "$json_out" <<'PROBE' || { rm -f "$json_out"; return 1; }
import json, sys
with open(sys.argv[1], encoding="utf-8") as handle:
    payload = json.load(handle)["decide"]  # one document per invocation, phases nested
mining, scoring = payload["mining"], payload["scoring"]
print(f"texts: {mining['texts']} · chunks: {mining['chunks']} (calls {mining['calls']}, "
      f"cached {mining['cached']}) · candidates: {mining['mined']}")
print(f"kept {mining['kept']} (pruned {mining['pruned']}, invented refs {mining['unknown_refs']}, "
      f"failed chunks {mining['failed_chunks']}) -> scored {scoring['scored']}")
print(f"snapshots: {payload['snapshots_written']} new in this run")
assert payload["snapshots_written"] > 0, "the decide layer must write snapshots from L0 data"
assert mining["texts"] > 50, "the lake must hold real collected text"
assert scoring["scored"] == payload["snapshots_written"], "every scored candidate is snapshotted"
assert payload["top"], "the ranked table must have rows"
assert all(0 <= row["mgs"] <= 100 for row in payload["top"]), "MGS stays inside 0-100"
PROBE
rm -f "$json_out"
if [ ${#hash1} -lt 32 ] || [ ${#hash2} -lt 32 ]; then
  printf 'replay determinism: no usable snapshot hash (%s, %s) - check failed rather than passed
' "$hash1" "$hash2"
  return 1
fi
if [ "$hash1" != "$hash2" ]; then
  printf 'replay determinism failed: %s != %s\n' "$hash1" "$hash2"
  return 1
fi
printf 'replay determinism: identical snapshot hash %s\n' "${hash1:0:16}"
}
check "P2 decide — rank, snapshot, deterministic replay" p2_probe
p3_probe() {
# P3 acceptance, offline: the Judge gate replays a REAL recorded provider answer through the
# gateway, schema, grounding rule and candidate table — no network, no quota, no cost.
local out
out=$(uv run python -m trend_analyst.pipeline.orchestrator --judge-replay tests/data/llm/judge_verdict.json --fresh --json 2>/dev/null)
printf '%s' "$out" > "${TMPDIR:-/tmp}/ta_p3.json"
uv run python - "${TMPDIR:-/tmp}/ta_p3.json" <<'PROBE' || return 1
import json, sys
with open(sys.argv[1], encoding="utf-8") as handle:
    payload = json.load(handle)
judge = payload["judge"]
judged = judge["judged"]
print(f"replayed: {judge['source']} · judged={judged} kept={judge['kept']} "
      f"dropped={judge['dropped']} unknown={judge['unknown_phrase']} "
      f"ungrounded={judge['ungrounded']} quotes_stripped={judge['removed_quotes']}")
assert judged >= 1, "the replay must apply at least one verdict"
assert judge["unknown_phrase"] == 0, "a batch must never apply another batch's verdict"
assert judge["batches"] >= 1
assert judge["prompt_tokens"] > 0, "the recording carries a real provider's token counts"
assert judge["status"] == "ok", judge["reason"]
PROBE
}
check "P3 judge — offline replay of a recorded verdict" p3_probe
p4_probe() {
# P4 acceptance, offline: every layer in order, single-shot, on recorded fixtures and
# recorded gate answers — no network, no spend. The run passes when collection and
# scoring finish, whatever they found.
local out
out=$(uv run python -m scripts.nightly --offline --dry-run --json 2>/dev/null)
printf '%s' "$out" > "${TMPDIR:-/tmp}/ta_p4.json"
uv run python - "${TMPDIR:-/tmp}/ta_p4.json" <<'PROBE' || return 1
import json, sys
with open(sys.argv[1], encoding="utf-8") as handle:
    payload = json.load(handle)
print(f"L0 {payload['l0']['status']} · decide {payload['decide']['status']} "
      f"({payload['decide']['scored']} scored) · judge {payload['judge']['status']} · "
      f"writer {payload['writer']['status']}")
assert payload["l0"]["status"] in {"ok", "partial", "degraded"}, payload["l0"]
assert payload["decide"]["scored"] > 0, "the decide layer must score candidates from the lake"
assert payload["judge"]["status"] in {"ok", "empty", "skipped"}, payload["judge"]
assert any("offline: replaying" in note for note in payload["notes"]), payload["notes"]
PROBE
}
check "P4 nightly — all layers run end to end" p4_probe
eval_probe() {
# Spec 8's eval half: the golden cases must still describe the system. Bands and labels are checked
# always; keep/drop only where a Judge verdict exists, which the report makes visible (as `partial`)
# rather than hiding behind a pass.
local out
out=$(uv run python -m evals.run_evals --json 2>/dev/null)
printf '%s' "$out" > "${TMPDIR:-/tmp}/ta_eval.json"
uv run python - "${TMPDIR:-/tmp}/ta_eval.json" <<'PROBE' || return 1
import json, sys
with open(sys.argv[1], encoding="utf-8") as handle:
    payload = json.load(handle)
checked = [r for r in payload["results"] if r["checks"]]
print(f"cases: {payload['total']} · verified: {payload['verified']} · partial: {payload['partial']} "
      f"(keep/drop unjudged) · failed: {payload['failed']} · unchecked: {payload['unchecked']}")
for result in checked[:2]:
    print(f"  {result['id'][:46]:<46} {result['checks']}")
assert payload["total"] >= 50, "spec 8 requires 50 golden cases; the set must not shrink"
assert checked, "at least one case must be checkable"
assert payload["failed"] == 0, [r["reasons"] for r in payload["results"] if r["reasons"]]
assert all(r["checks"].get("score_band", True) for r in checked), "score bands must hold"
assert all(r["checks"].get("fad_label", True) for r in checked), "fad labels must hold"
# The unverified check is stated, not glossed: the cases whose keep/drop has no verdict yet are
# counted, so "0 failed" can never be read as "all 50 confirmed".
print(f"  note: {payload['pending_checks']} case(s) await a Judge verdict for keep/drop")
PROBE
}
check "evals — 50 golden cases still describe the system" eval_probe

docs_probe() {
# Spec 5/6's bars, as assertions rather than as prose about prose. These are cheap and they fail
# for the right reasons: a missing runbook, a tier list that lost a line, a cost table without the
# providers, or a troubleshooting section that dropped one of the five named failures.
uv run python - <<'PROBE' || return 1
from pathlib import Path

# Case-insensitive for the same reason a spell-check is: the bar is about content, not capitalisation.
agent = Path("AGENT.md").read_text(encoding="utf-8")
setup = Path("USER_SETUP.md").read_text(encoding="utf-8")
agent_lower, setup_lower = agent.lower(), setup.lower()

lines = len(agent.splitlines())
assert lines <= 110, f"AGENT.md is {lines} lines; the bar is a short ops note (~80)"
for needle in (
    "Always do", "Ask first", "Never do",
    "429", "Quota burn", "keep-rate", "Eval baseline drop",
    "SYMPTOM", "EVIDENCE", "ATTEMPTED", "PROPOSED", "REVERSAL",
    "Rollback rule", "one command",
):
    assert needle.lower() in agent_lower, f"AGENT.md is missing {needle!r}"
print(f"AGENT.md: {lines} lines, 5 runbooks, 3 tiers, escalation + rollback present")

# The human's checklist: every bar item from brief 6 must be findable.
for needle in (
    "Where to create it", "Free tier", "Verify command",
    "Expected wait", "cron", "workflow_dispatch",
    "Cost at expected volume", "would trigger a paid tier",
    "Troubleshooting", "wrong region", "OAuth expiry", "quota is zero",
    "Postgres", "key is rejected",
):
    assert needle.lower() in setup_lower, f"USER_SETUP.md is missing {needle!r}"
providers = ("Gemini", "Groq", "Cerebras", "Ollama", "eBay", "GitHub", "Best Buy", "Serper",
             "Product Hunt", "Walmart", "SearchAPI")
missing = [name for name in providers if name not in setup]
assert not missing, f"the cost/key tables are missing {missing}"
print(f"USER_SETUP.md: key table + cost table for {len(providers)} providers, 5 failure modes")
PROBE
}
check "P5 documents — AGENT.md and USER_SETUP.md meet the brief's bars" docs_probe

# --- summary -----------------------------------------------------------------
header "Summary"
if [ "$failures" -eq 0 ]; then
  printf 'GATE: PASS (%s pending)\n' "$pendings"
  exit 0
fi
printf 'GATE: FAIL — %s check(s) failed\n' "$failures"
exit 1
