#!/usr/bin/env bash
# Trend Analyst — the gate.
#
# Runs every check the build brief requires and prints markdown with RAW output, so
# evidence is generated rather than remembered:
#
#     bash scripts/gate.sh > docs/evidence/P0-gate.md
#
# Checks that cannot pass yet because their phase has not landed are reported as
# PENDING with the reason, and do not fail the gate. That is deliberate: a gate that
# has to be edited to stay honest stops being evidence.
#
# Exit code: 0 when every runnable check passes, 1 otherwise.
set -uo pipefail

cd "$(dirname "$0")/.." || exit 2
export UV_PYTHON_DOWNLOADS=never UV_NO_MANAGED_PYTHON=1

failures=0
pendings=0

header() {
  printf '\n### %s\n\n' "$1"
}

check() { # check <title> <command...>
  local title="$1"
  shift
  header "$title"
  printf '```console\n$ %s\n' "$*"
  local out
  if out="$("$@" 2>&1)"; then
    printf '%s\n```\n\n**RESULT: PASS**\n' "$out"
  else
    printf '%s\n```\n\n**RESULT: FAIL (exit %s)**\n' "$out" "$?"
    failures=$((failures + 1))
  fi
}

pending() { # pending <title> <reason> <command...>
  local title="$1" reason="$2"
  shift 2
  pendings=$((pendings + 1))
  header "$title"
  printf '```console\n$ %s\n' "$*"
  printf '%s\n```\n\n**RESULT: PENDING — %s**\n' "$("$@" 2>&1)" "$reason"
}

# --- environment -------------------------------------------------------------
printf '# Trend Analyst — evidence log\n\n'
printf 'Generated by `scripts/gate.sh` on %s.\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
printf '\nInterpreter: `%s`\n' "$(uv run python -c 'import sys; print(sys.version.split()[0] + " (" + sys.executable + ")")' 2>/dev/null)"

# --- always runnable ---------------------------------------------------------
check "pytest — no database, no network" uv run pytest -q -m "not db"
check "ruff — lint clean" uv run ruff check .
check "mypy — strict, python_version=3.12" uv run mypy src config

# --- configuration ------------------------------------------------------------
config_cli_probe() {
  uv run python - <<'PY'
import json
import subprocess
import sys

out = subprocess.run(
    [sys.executable, "-m", "config.cli", "show", "--json"],
    capture_output=True,
    text=True,
    check=True,
)
data = json.loads(out.stdout)
layers = ", ".join(
    f"{layer['label']}={'loaded' if layer['exists'] else 'absent'}" for layer in data["layers"]
)
redacted = data["settings"]["db"]["url"] in ("", "***")
print(f"layers (high->low): {layers}")
print(f"credentials configured: {sum(1 for ok in data['credentials_configured'].values() if ok)}")
print(f"db.url redacted: {redacted}")
assert redacted, "the config CLI leaked a secret"
PY
}
check "config CLI — every layer resolved, secrets redacted" config_cli_probe

# --- registry ------------------------------------------------------------------
registry_probe() {
  uv run python - <<'PY'
import subprocess
import sys

out = subprocess.run(
    [sys.executable, "-m", "config.cli", "registry", "--json"],
    capture_output=True,
    text=True,
    check=True,
)
import json

data = json.loads(out.stdout)
summary = data["summary"]
print(
    f"{summary['total']} sources ({summary['tier_s']} Tier S, {summary['tier_a']} Tier A) · "
    f"{summary['enabled']} enabled, {summary['disabled']} disabled"
)
print(f"L0 collect: {summary['l0']} · L2 enrich: {summary['l2']}")
print(f"execution order starts: {', '.join(s['id'] for s in data['sources'][:3])} ...")
print(f"egress allowlist entries: {sum(len(v) for v in data['allowed_domains'].values())}")

l0 = [s for s in data["sources"] if "L0" in s["layers"]]
assert all(s["tier"] == "S" for s in l0), "Tier A slipped into L0"
assert all(s["enabled"] for s in l0), "an L0 source is disabled"
assert all(not s["enabled"] for s in data["sources"] if s["tier"] == "A"), (
    "a Tier-A source is enabled without its credential being verified"
)
PY
}
check "source registry — catalog, execution order, Tier-A never in L0" registry_probe

# --- L0 collection, replayed from the recorded fixtures (P1) ------------------
l0_replay_probe() {
  uv run python - <<'PY'
import json
import subprocess
import sys

SOURCES = ["--source", "hn_firebase", "--source", "wiki_pageviews", "--source", "arctic_shift"]

def run() -> dict:
    out = subprocess.run(
        [sys.executable, "-m", "trend_analyst.pipeline.orchestrator",
         "--fixtures", "tests/data", "--json", *SOURCES],
        capture_output=True, text=True, check=True,
    )
    # The CLI emits ONE document per invocation; a plain L0 run nests it under "l0".
    return json.loads(out.stdout)["l0"]

first = run()
second = run()
print(f"run 1: status={first['status']} signals={first['items_new']} "
      f"requests={first['quota_spent']}")
print(f"run 2: status={second['status']} signals={second['items_new']} "
      f"requests={second['quota_spent']}")
for outcome in second["outcomes"]:
    print(f"  {outcome['source_id']:<20} {outcome['status']:<8} "
          f"new={outcome['items_new']:<4} parsed={outcome['signals_parsed']:<4} "
          f"requests={outcome['quota_spent']}")
assert second["items_new"] == 0, "a repeated L0 run must store no new signals"
assert all(o["signals_parsed"] == 0 for o in second["outcomes"]), (
    "a repeated L0 run must not re-parse identical payloads"
)
PY
}
check "L0 replay — repeated run stores and parses nothing new" l0_replay_probe

# --- registry → database sync (P0-T6) -----------------------------------------
if uv run python -c "
import socket, sys
s = socket.socket(); s.settimeout(2)
sys.exit(0 if s.connect_ex(('127.0.0.1', 5432)) == 0 else 1)
" 2>/dev/null; then
  check "registry sync — second run is a no-op" uv run python -m scripts.sync_sources
  check "registry sync — idempotent (dry run reports zero changes)" \
    uv run python -m scripts.sync_sources --dry-run
else
  pending "registry sync" "no Postgres reachable on 127.0.0.1:5432" \
    uv run python -m scripts.sync_sources
fi

# --- needs Postgres ----------------------------------------------------------
if uv run python -c "
import socket, sys
s = socket.socket(); s.settimeout(2)
sys.exit(0 if s.connect_ex(('127.0.0.1', 5432)) == 0 else 1)
" 2>/dev/null; then
  check "pytest — full suite against local Postgres + pgvector" uv run pytest -q
  if [ -f alembic.ini ] && compgen -G "migrations/versions/*.py" >/dev/null; then
    check "alembic — upgrade head" uv run alembic upgrade head
    check "alembic — zero drift between models and migrations" uv run alembic check
  else
    pending "alembic — upgrade head" "migrations land in bean P0-T5" uv run alembic upgrade head
  fi
else
  pending "pytest — full suite" "no Postgres reachable on 127.0.0.1:5432 (run: wsl -d Ubuntu -u root -- bash scripts/provision_pg.sh)" uv run pytest -q
fi

# --- health (P0-T7) ------------------------------------------------------------
# The CLI's contract is checked here; the *state* it reports (empty-but-healthy) is
# asserted in the test suite against the isolated database, because the development
# database legitimately accumulates real runs.
health_probe() {
  uv run python - <<'PY'
import json
import subprocess
import sys

out = subprocess.run(
    [sys.executable, "-m", "trend_analyst.health", "--json"],
    capture_output=True,
    text=True,
    check=False,
)
payload = json.loads(out.stdout)
status = payload["status"]
expected = {"healthy": 0, "degraded": 1, "down": 2}[status]
print(f"status: {status} (exit {out.returncode}, expected {expected})")
print(f"database: {'ok' if payload['database']['ok'] else 'DOWN'}")
print(f"sources: {len(payload['sources'])} · reasons: {payload.get('reasons')}")
assert out.returncode == expected, f"exit code must match the status ({status})"
assert payload["database"]["ok"], "the database must be reachable for this check"
PY
}
check "health CLI — valid report, exit code matches status" health_probe
p2_probe() {
# P2 acceptance: the ranked table renders end-to-end from L0 data, snapshots are versioned,
# and replaying the same lake reproduces the same scores (spec 5.4, hash-asserted in CI).
local first second hash1 hash2
first=$(uv run python -m trend_analyst.pipeline.orchestrator --layers L1,L3 --top 3 --json 2>/dev/null)
second=$(uv run python -m trend_analyst.pipeline.orchestrator --layers L1,L3 --top 3 --json 2>/dev/null)
hash1=$(printf '%s' "$first" | uv run python -c 'import json,sys; print(json.load(sys.stdin)["decide"]["snapshot_hash"])')
hash2=$(printf '%s' "$second" | uv run python -c 'import json,sys; print(json.load(sys.stdin)["decide"]["snapshot_hash"])')
json_out=$(mktemp)
printf '%s' "$first" > "$json_out"
# NB: the payload goes through a file, not a pipe: with `python - <<HEREDOC` the heredoc IS
# stdin, so a piped payload is never read (the first draft of this check did exactly that and
# failed silently while still reporting PASS).
uv run python - "$json_out" <<'PROBE' || { rm -f "$json_out"; return 1; }
import json, sys
with open(sys.argv[1], encoding="utf-8") as handle:
    payload = json.load(handle)["decide"]  # one document per invocation, phases nested
mining, scoring = payload["mining"], payload["scoring"]
print(f"texts: {mining['texts']} · ngrams: {mining['ngrams']} · candidates: {mining['mined']}")
print(f"kept {mining['kept']} (pruned {mining['pruned']}, unmatched {mining['unmatched']}) "
      f"-> scored {scoring['scored']}")
print(f"snapshots: {payload['snapshots_written']} new in this run")
assert payload["snapshots_written"] > 0, "the decide layer must write snapshots from L0 data"
assert mining["texts"] > 50, "the lake must hold real collected text"
assert scoring["scored"] == payload["snapshots_written"], "every scored candidate is snapshotted"
assert payload["top"], "the ranked table must have rows"
assert all(0 <= row["mgs"] <= 100 for row in payload["top"]), "MGS stays inside 0-100"
PROBE
rm -f "$json_out"
if [ ${#hash1} -lt 32 ] || [ ${#hash2} -lt 32 ]; then
  printf 'replay determinism: no usable snapshot hash (%s, %s) - check failed rather than passed
' "$hash1" "$hash2"
  return 1
fi
if [ "$hash1" != "$hash2" ]; then
  printf 'replay determinism failed: %s != %s\n' "$hash1" "$hash2"
  return 1
fi
printf 'replay determinism: identical snapshot hash %s\n' "${hash1:0:16}"
}
check "P2 decide — rank, snapshot, deterministic replay" p2_probe
p3_probe() {
# P3 acceptance, offline: the Judge gate replays a REAL recorded provider answer through the
# gateway, schema, grounding rule and candidate table — no network, no quota, no cost.
local out
out=$(uv run python -m trend_analyst.pipeline.orchestrator --judge-replay tests/data/llm/judge_verdict.json --fresh --json 2>/dev/null)
printf '%s' "$out" > "${TMPDIR:-/tmp}/ta_p3.json"
uv run python - "${TMPDIR:-/tmp}/ta_p3.json" <<'PROBE' || return 1
import json, sys
with open(sys.argv[1], encoding="utf-8") as handle:
    payload = json.load(handle)
judge = payload["judge"]
judged = judge["judged"]
print(f"replayed: {judge['source']} · judged={judged} kept={judge['kept']} "
      f"dropped={judge['dropped']} unknown={judge['unknown_phrase']} "
      f"ungrounded={judge['ungrounded']} quotes_stripped={judge['removed_quotes']}")
assert judged >= 1, "the replay must apply at least one verdict"
assert judge["unknown_phrase"] == 0, "a batch must never apply another batch's verdict"
assert judge["batches"] >= 1
assert judge["prompt_tokens"] > 0, "the recording carries a real provider's token counts"
assert judge["status"] == "ok", judge["reason"]
PROBE
}
check "P3 judge — offline replay of a recorded verdict" p3_probe
p4_probe() {
# P4 acceptance, offline: every layer in order, then the ledger reconciled to zero unexplained
# spend. This is the brief's bar ("quota ledger balanced to zero unexplained spend") run end to end
# on recorded fixtures and recorded gate answers, so it costs nothing and can run on every gate.
local out
out=$(uv run python -m scripts.nightly --offline --dry-run --json 2>/dev/null)
printf '%s' "$out" > "${TMPDIR:-/tmp}/ta_p4.json"
uv run python - "${TMPDIR:-/tmp}/ta_p4.json" <<'PROBE' || return 1
import json, sys
with open(sys.argv[1], encoding="utf-8") as handle:
    payload = json.load(handle)
print(f"L0 {payload['l0']['status']} · decide {payload['decide']['status']} "
      f"({payload['decide']['scored']} scored) · judge {payload['judge']['status']} · "
      f"writer {payload['writer']['status']}")
rec = payload["reconciliation"]
print(f"ledger: {rec['rows']} rows, {rec['spend_total']} units, {rec['explained']} explained, "
      f"balanced={rec['balanced']}")
assert payload["l0"]["status"] in {"ok", "partial", "degraded"}, payload["l0"]
assert payload["decide"]["scored"] > 0, "the decide layer must score candidates from the lake"
assert rec["balanced"], rec["unexplained"][:3]
assert rec["rows"] > 0, "the nightly run must have spent something to reconcile"
assert any("offline: replaying" in note for note in payload["notes"]), payload["notes"]
PROBE
}
check "P4 nightly — all layers then a balanced ledger" p4_probe
# --- summary -----------------------------------------------------------------
header "Summary"
if [ "$failures" -eq 0 ]; then
  printf 'GATE: PASS (%s pending)\n' "$pendings"
  exit 0
fi
printf 'GATE: FAIL — %s check(s) failed\n' "$failures"
exit 1
